name: main

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: setup go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "1.24.0"

      - name: build
        run: |
          cd app
          go build -v ./...
